- hosts: post
  connection: chroot
  sudo: false
  gather_facts: false

  vars:
    centos_version: 7
    cdlabel: "centos{{ centos_version }}-mini"
    hostname: "centos{{ centos_version }}-mini"
    livecd_user: centos
    root_password: centos

    # Variables below not used directly in playbook. Used by generate_config.py to create basic kickstart file.

    lang: en_US.UTF-8
    keyboard: us
    timezone: Asia/Jerusalem
    partition_size: 4096

    repos_list:
      - { name: 'a-base', baseurl: 'http://mirror.isoc.org.il/pub/centos/{{ centos_version }}/os/$basearch' }
      - { name: 'a-updates', baseurl: 'http://mirror.isoc.org.il/pub/centos/{{ centos_version }}/updates/$basearch' }

    # End of variable block used by generate_config.py

  roles:
    - livecd-pre-common
    # Add your ansible roles here
    # - epel-repo
    # - centos-sshd-service
    - livecd-pxe-common
    - livecd-post-common


- hosts: post-nochroot
  connection: local
  sudo: false
  gather_facts: false

  roles:
    - livecd-isolinux-common
